version: 0.1

phases:
  install:
    commands:
      - echo Installing rdk...
      - pip install .
      - pip install rdklib
  pre_build:
    commands:
      - echo Starting tests
      - rdk init
  build:
    commands:

      - python3 testing/regional_test.py
  post_build:
    commands:
      - echo Build completed on `date`
